services:
  api-sportreg-prod:
    container_name: api-sportreg-prod
    build: ./api
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    environment:
        PRODUCTION: $PRODUCTION
        MONGO_USERNAME: $MONGO_USERNAME
        MONGO_PASSWORD: $MONGO_PASSWORD
        MONGO_CLUSTER: $MONGO_CLUSTER
    ports:
      - "80:80"
